### ISSUE TITLE
CI: Ironic job not working, error when enrolling the node

### ISSUE THREAD

**Issue by EmilienM** [gophercloud/gophercloud#2375]
It broke on April 3rd:
https://github.com/gophercloud/gophercloud/actions/workflows/functional-baremetal.yaml

The root cause is yet to be identified but it seems like an issue with ipmitool not able to reach the vbmc:

```
Apr  6 19:03:20 fv-az196-963 ironic-conductor[103533]: #033[00;32mDEBUG oslo_concurrency.processutils [#033[01;36mNone req-7f90f508-18cb-4762-b8b1-49ed749746d2 #033[00;36mNone None#033[00;32m] #033[01;35m#033[00;32mCMD "ipmitool -I lanplus -H 10.1.1.120 -L ADMINISTRATOR -p 6230 -U admin -R 1 -N 5 -f /tmp/tmp0td32boa power status" returned: 1 in 10.039s#033[00m #033[00;33m{{(pid=103533) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}#033[00m#033[00m
Apr  6 19:03:20 fv-az196-963 ironic-conductor[103533]: #033[00;32mDEBUG oslo_concurrency.processutils [#033[01;36mNone req-7f90f508-18cb-4762-b8b1-49ed749746d2 #033[00;36mNone None#033[00;32m] #033[01;35m#033[00;32m'ipmitool -I lanplus -H 10.1.1.120 -L ADMINISTRATOR -p 6230 -U admin -R 1 -N 5 -f /tmp/tmp0td32boa power status' failed. Not Retrying.#033[00m #033[00;33m{{(pid=103533) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:473}}#033[00m#033[00m
Apr  6 19:03:20 fv-az196-963 ironic-conductor[103533]: #033[01;33mWARNING ironic.drivers.modules.ipmitool [#033[01;36mNone req-7f90f508-18cb-4762-b8b1-49ed749746d2 #033[00;36mNone None#033[01;33m] #033[01;35m#033[01;33mIPMI Error encountered, retrying "ipmitool -I lanplus -H 10.1.1.120 -L ADMINISTRATOR -p 6230 -U admin -R 1 -N 5 -f /tmp/tmp0td32boa power status" for node 96214ca7-e0d6-4ffb-8dcf-d40e32564c28. Error: Unexpected error while running command.
Apr  6 19:03:20 fv-az196-963 ironic-conductor[103533]: Command: ipmitool -I lanplus -H 10.1.1.120 -L ADMINISTRATOR -p 6230 -U admin -R 1 -N 5 -f /tmp/tmp0td32boa power status
Apr  6 19:03:20 fv-az196-963 ironic-conductor[103533]: Exit code: 1
Apr  6 19:03:20 fv-az196-963 ironic-conductor[103533]: Stdout: ''
Apr  6 19:03:20 fv-az196-963 ironic-conductor[103533]: Stderr: 'Set Session Privilege Level to ADMINISTRATOR failed\nError: Unable to establish IPMI v2 / RMCP+ session\nClose Session command failed\n'#033[00m: oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.#033[00m
```

Not sure if this is a red herring but we also see this vbmc error:
```
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]: 2022-04-06 19:04:10,646 103942 ERROR VirtualBMC [-] Shutdown vBMC for domain node-0, cause 'ServerSession' object has no attribute 'remseqnumber'
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]: Traceback (most recent call last):
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]:   File "/opt/stack/virtualbmc/virtualbmc/manager.py", line 140, in vbmc_runner
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]:     vbmc.listen(timeout=CONF['ipmi']['session_timeout'])
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]:   File "/opt/stack/pyghmi/pyghmi/ipmi/bmc.py", line 192, in listen
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]:     ipmisession.Session.wait_for_rsp(timeout)
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]:   File "/opt/stack/pyghmi/pyghmi/ipmi/private/session.py", line 1207, in wait_for_rsp
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]:     relsession.process_pktqueue()
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]:   File "/opt/stack/pyghmi/pyghmi/ipmi/private/session.py", line 1325, in process_pktqueue
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]:     self._handle_ipmi_packet(pkt[0], sockaddr=pkt[1], qent=pkt)
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]:   File "/opt/stack/pyghmi/pyghmi/ipmi/private/session.py", line 1376, in _handle_ipmi_packet
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]:     self._handle_ipmi2_packet(data)
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]:   File "/opt/stack/pyghmi/pyghmi/ipmi/private/session.py", line 1429, in _handle_ipmi2_packet
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]:     if (self.remseqnumber is not None
Apr  6 19:04:10 fv-az196-963 vbmcd[103942]: AttributeError: 'ServerSession' object has no attribute 'remseqnumber'
```

This causes all the baremetal jobs to fail, when enrolling the node during the devstack install:
```
 +++ /opt/stack/ironic/devstack/lib/ironic:enroll_nodes:2470 :   openstack baremetal node create --uuid 4c1acf49-f683-4e03-bd0c-67f3b327f015 --chassis 0b54575f-f031-4723-b4c3-ef76a7ca19fd --driver ipmi --name node-0 --resource-class baremetal --property cpu_arch=x86_64 --driver-info ipmi_address=10.1.1.135 --driver-info ipmi_username=admin --driver-info ipmi_password=password --driver-info ipmi_port=6230 -f value -c uuid
++ /opt/stack/ironic/devstack/lib/ironic:enroll_nodes:2470 :   node_id=4c1acf49-f683-4e03-bd0c-67f3b327f015
++ /opt/stack/ironic/devstack/lib/ironic:enroll_nodes:2471 :   die_if_not_set 2471 node_id 'Failed to create node'
++ functions-common:die_if_not_set:216      :   local exitcode=0
++ /opt/stack/ironic/devstack/lib/ironic:enroll_nodes:2472 :   node_uuids+=' 4c1acf49-f683-4e03-bd0c-67f3b327f015'
++ /opt/stack/ironic/devstack/lib/ironic:enroll_nodes:2474 :   [[ -n CUSTOM_GOLD ]]
++ /opt/stack/ironic/devstack/lib/ironic:enroll_nodes:2475 :   openstack baremetal node add trait 4c1acf49-f683-4e03-bd0c-67f3b327f015 CUSTOM_GOLD
Added trait CUSTOM_GOLD
++ /opt/stack/ironic/devstack/lib/ironic:enroll_nodes:2478 :   openstack baremetal node manage 4c1acf49-f683-4e03-bd0c-67f3b327f015 --wait 120
Node 4c1acf49-f683-4e03-bd0c-67f3b327f015 failed to reach state manageable. It's in unexpected stable state enroll
Waiting for provision state manageable on node 4c1acf49-f683-4e03-bd0c-67f3b327f015
++ /opt/stack/ironic/devstack/lib/ironic:enroll_nodes:2479 :   die 2479 'Node did not reach manageable state in 120 seconds'
```

**Comment by elfosardo** [comment]
looks like this change https://opendev.org/x/pyghmi/commit/6836bfffdde9e7031a64bc7da78a8d22980980f4 introduced a change that check for the sequence number before the login ever happen, causing a failure during the first login tentative

**Comment by EmilienM** [comment]
Potential fix: https://review.opendev.org/c/x/pyghmi/+/836911
