### ISSUE TITLE
Panic in 'ExtractIntoStructPtr'

### ISSUE THREAD

**Issue by bobuhiro11** [gophercloud/gophercloud#2872]
Accidentally passing nil to 'ExtractIntoStructPtr' function would cause panic.
You can reproduce this by adding the following code to testing/results_test.go .

```go
func TestUnmarshalNilPointer(t *testing.T) {
        var x *TestPerson

        err1 := gophercloud.Result{}.ExtractIntoStructPtr(&x, "")
        err2 := gophercloud.Result{}.ExtractIntoStructPtr(nil, "")

        th.AssertErr(t, err1)
        th.AssertErr(t, err2)
}
```

Outputs are as follows:

```bash
ubuntu2204:~/gophercloud$ go test ./testing/ -run TestUnmarshalNilPointer -v
=== RUN   TestUnmarshalNilPointer
--- FAIL: TestUnmarshalNilPointer (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x6d12d2]

goroutine 6 [running]:
testing.tRunner.func1.2({0x71d100, 0x9daca0})
        /usr/lib/go-1.20/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /usr/lib/go-1.20/src/testing/testing.go:1529 +0x39f
panic({0x71d100, 0x9daca0})
        /usr/lib/go-1.20/src/runtime/panic.go:884 +0x213
github.com/gophercloud/gophercloud.Result.ExtractIntoStructPtr({{0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}}, {0x0, 0x0}, {0x0, 0x0})
        /home/bobuhiro11/gophercloud/results.go:188 +0xb2
github.com/gophercloud/gophercloud/testing.TestUnmarshalNilPointer(0x0?)
        /home/bobuhiro11/gophercloud/testing/results_test.go:120 +0x6e
testing.tRunner(0xc00013e4e0, 0x7a8b98)
        /usr/lib/go-1.20/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/lib/go-1.20/src/testing/testing.go:1629 +0x3ea
FAIL    github.com/gophercloud/gophercloud/testing      0.006s
FAIL
```

**Comment by pierreprinetti** [comment]
Thank you for this high-quality report featuring a minimal reproducer!

**Comment by pierreprinetti** [comment]
Actually, your reproducer is misleading.

The first line (where you pass a pointer to a pointer to `TestPerson` (`**TestPerson`) correctly errors.

For reference: https://go.dev/play/p/XN6nHpe52yp

Could you find a case where the panic happens, in which you're not passing the literal `nil`?

**Comment by pierreprinetti** [comment]
@bobuhiro11 
By any chance: have you hit a panic in some real-world application of this code?

**Comment by bobuhiro11** [comment]
@pierreprinetti 
I noticed this during development and decided to validate it on the application side.
I don't have a problem with it.
